spring.application.name=gestion-estudiantes-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_estudiantes_spring_boot
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (útil para depuración)
spring.jpa.show-sql=true

# Formatea las consultas SQL para mejor legibilidad
spring.jpa.properties.hibernate.format_sql=true
